### ISSUE TITLE
How to hide the alertview.

### ISSUE THREAD

**Issue by icodebuster** [josshad/EHPlainAlert#5]
Is there a way to automatically hide the alertview based on a button click. 

My use case when the user taps on Sign Up button the user is taken to a signup screen, here I am able to see the previous screens alertview. So basically I wanted a method which can hide all the alertviews at once.

Any help much appreciated.

**Comment by josshad** [comment]
Hello.

I added this functionality in 1.2.6

**Comment by icodebuster** [comment]
@josshad 

Sorry for raising the issue, I was using 1.2.1.
Its working as expected

👍
