### ISSUE TITLE
Detect if alert is pressed?

### ISSUE THREAD

**Issue by remotewhiteboard** [josshad/EHPlainAlert#8]
Is there a way to detect if they pressed on the alert, and then send them somewhere?

**Comment by josshad** [comment]
EHPlainAlert * ehAlert = [[EHPlainAlert alloc] initWithTitle:@"Hmm..." message:@"Tap for information" type:ViewAlertInfo];
    ehAlert.action = ^{
        [[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"https://github.com/josshad/EHPlainAlert"]];
    };
    ehAlert.messageColor = [UIColor blueColor];
    ehAlert.iconImage = nil;
    [ehAlert show];

This example will open safari on tap.
